name: Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 4: Compile TypeScript
      - name: Compile TypeScript
        run: |
          tsc src/main.ts

      # Step 5: Run Node.js Script
      - name: Run Node.js Script
        run: |
          OUTPUT=$(node src/main.js)
          echo "$OUTPUT"
